/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ISS;

/**
 *
 * @author PEGASUS
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();
        inputMotivo = new javax.swing.JScrollPane();
        jTextinputMotivo = new javax.swing.JTextArea();
        LabelUserMotivo = new javax.swing.JLabel();
        inputApellidoM = new javax.swing.JScrollPane();
        jTextInputApellidoM = new javax.swing.JTextArea();
        LabelUserApellidoP = new javax.swing.JLabel();
        inputApellidoP = new javax.swing.JScrollPane();
        jTextInputApellidoP = new javax.swing.JTextArea();
        LabelUserApellidoM = new javax.swing.JLabel();
        inputName = new javax.swing.JScrollPane();
        jTextInputName = new javax.swing.JTextArea();
        LabelUserName = new javax.swing.JLabel();
        btnIdentificacion = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        irRegistrar = new javax.swing.JButton();
        btnEndUser = new javax.swing.JButton();
        meessege = new javax.swing.JLabel();
        userCarr = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        nameSist = new javax.swing.JLabel();
        nameUACM = new javax.swing.JLabel();
        fondoRojo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AccesoUACM");
        setMaximumSize(new java.awt.Dimension(1300, 700));
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagen.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 420, 30));

        inputMotivo.setBorder(null);
        inputMotivo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        inputMotivo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        inputMotivo.setMaximumSize(new java.awt.Dimension(170, 130));
        inputMotivo.setMinimumSize(new java.awt.Dimension(170, 130));
        inputMotivo.setPreferredSize(new java.awt.Dimension(170, 130));

        jTextinputMotivo.setColumns(20);
        jTextinputMotivo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextinputMotivo.setLineWrap(true);
        jTextinputMotivo.setRows(5);
        jTextinputMotivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputMotivo.setViewportView(jTextinputMotivo);

        getContentPane().add(inputMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 420, 140));

        LabelUserMotivo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelUserMotivo.setForeground(new java.awt.Color(255, 255, 255));
        LabelUserMotivo.setText("Motivo de visita");
        LabelUserMotivo.setToolTipText("");
        getContentPane().add(LabelUserMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        inputApellidoM.setBorder(null);
        inputApellidoM.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        inputApellidoM.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        inputApellidoM.setMaximumSize(new java.awt.Dimension(170, 80));
        inputApellidoM.setMinimumSize(new java.awt.Dimension(170, 80));
        inputApellidoM.setPreferredSize(new java.awt.Dimension(170, 80));
        inputApellidoM.setRowHeaderView(null);

        jTextInputApellidoM.setColumns(20);
        jTextInputApellidoM.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextInputApellidoM.setRows(5);
        inputApellidoM.setViewportView(jTextInputApellidoM);

        getContentPane().add(inputApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 420, 40));

        LabelUserApellidoP.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelUserApellidoP.setForeground(new java.awt.Color(255, 255, 255));
        LabelUserApellidoP.setText("Apellido Paterno");
        LabelUserApellidoP.setToolTipText("");
        getContentPane().add(LabelUserApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        inputApellidoP.setBorder(null);
        inputApellidoP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        inputApellidoP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        inputApellidoP.setMaximumSize(new java.awt.Dimension(170, 80));
        inputApellidoP.setMinimumSize(new java.awt.Dimension(170, 80));
        inputApellidoP.setPreferredSize(new java.awt.Dimension(170, 80));
        inputApellidoP.setRowHeaderView(null);

        jTextInputApellidoP.setColumns(20);
        jTextInputApellidoP.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextInputApellidoP.setRows(5);
        inputApellidoP.setViewportView(jTextInputApellidoP);

        getContentPane().add(inputApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 420, 40));

        LabelUserApellidoM.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelUserApellidoM.setForeground(new java.awt.Color(255, 255, 255));
        LabelUserApellidoM.setText("Apellido Materno");
        getContentPane().add(LabelUserApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        inputName.setBorder(null);
        inputName.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        inputName.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        inputName.setMaximumSize(new java.awt.Dimension(170, 80));
        inputName.setMinimumSize(new java.awt.Dimension(170, 80));
        inputName.setPreferredSize(new java.awt.Dimension(170, 80));
        inputName.setRowHeaderView(null);

        jTextInputName.setColumns(20);
        jTextInputName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextInputName.setRows(5);
        inputName.setViewportView(jTextInputName);

        getContentPane().add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 420, 40));

        LabelUserName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        LabelUserName.setText("Nombre");
        getContentPane().add(LabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        btnIdentificacion.setBackground(new java.awt.Color(204, 204, 255));
        btnIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnIdentificacion.setText("Selecionar Identificadión");
        btnIdentificacion.setToolTipText("");
        btnIdentificacion.setBorder(null);
        btnIdentificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIdentificacion.setMaximumSize(new java.awt.Dimension(140, 30));
        btnIdentificacion.setMinimumSize(new java.awt.Dimension(140, 30));
        btnIdentificacion.setPreferredSize(new java.awt.Dimension(140, 30));
        getContentPane().add(btnIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 220, -1));

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setMaximumSize(new java.awt.Dimension(120, 30));
        btnGuardar.setMinimumSize(new java.awt.Dimension(120, 30));
        btnGuardar.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 110, -1));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setMaximumSize(new java.awt.Dimension(90, 30));
        btnRegresar.setMinimumSize(new java.awt.Dimension(90, 30));
        btnRegresar.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 90, -1));

        irRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        irRegistrar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        irRegistrar.setText("Visitante");
        irRegistrar.setBorder(null);
        irRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irRegistrar.setMaximumSize(new java.awt.Dimension(90, 30));
        irRegistrar.setMinimumSize(new java.awt.Dimension(90, 30));
        irRegistrar.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(irRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        btnEndUser.setBackground(new java.awt.Color(204, 204, 255));
        btnEndUser.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEndUser.setText("End User");
        btnEndUser.setBorder(null);
        btnEndUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEndUser.setMaximumSize(new java.awt.Dimension(90, 30));
        btnEndUser.setMinimumSize(new java.awt.Dimension(90, 30));
        btnEndUser.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(btnEndUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 90, -1));

        meessege.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        meessege.setForeground(new java.awt.Color(255, 255, 255));
        meessege.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        meessege.setText("Mensage");
        meessege.setMaximumSize(new java.awt.Dimension(300, 45));
        meessege.setMinimumSize(new java.awt.Dimension(300, 45));
        meessege.setPreferredSize(new java.awt.Dimension(300, 45));
        getContentPane().add(meessege, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 490, -1));

        userCarr.setBackground(new java.awt.Color(255, 0, 51));
        userCarr.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        userCarr.setForeground(new java.awt.Color(255, 255, 255));
        userCarr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCarr.setText("Ingeieria en transporte Urbanos");
        userCarr.setMaximumSize(new java.awt.Dimension(300, 25));
        userCarr.setMinimumSize(new java.awt.Dimension(300, 25));
        userCarr.setPreferredSize(new java.awt.Dimension(300, 25));
        getContentPane().add(userCarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 500, -1));

        userName.setBackground(new java.awt.Color(255, 102, 0));
        userName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("Ramirez Ortega Artiga Sandobal");
        userName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userName.setMaximumSize(new java.awt.Dimension(300, 25));
        userName.setMinimumSize(new java.awt.Dimension(300, 25));
        userName.setName(""); // NOI18N
        userName.setPreferredSize(new java.awt.Dimension(300, 25));
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 480, -1));

        imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icono.png"))); // NOI18N
        imgUser.setText("jLabel1");
        imgUser.setMaximumSize(new java.awt.Dimension(250, 250));
        imgUser.setMinimumSize(new java.awt.Dimension(250, 250));
        imgUser.setName(""); // NOI18N
        imgUser.setPreferredSize(new java.awt.Dimension(250, 250));
        getContentPane().add(imgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        nameSist.setFont(new java.awt.Font("Tomorrow", 1, 40)); // NOI18N
        nameSist.setForeground(new java.awt.Color(204, 204, 204));
        nameSist.setText("Acceso UACM");
        getContentPane().add(nameSist, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        nameUACM.setBackground(new java.awt.Color(204, 0, 0));
        nameUACM.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        nameUACM.setForeground(new java.awt.Color(255, 255, 255));
        nameUACM.setText("UACM");
        nameUACM.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        nameUACM.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        nameUACM.setFocusTraversalPolicyProvider(true);
        nameUACM.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(nameUACM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 100));

        fondoRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo1.jpg"))); // NOI18N
        fondoRojo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        fondoRojo.setMaximumSize(new java.awt.Dimension(3000, 3000));
        fondoRojo.setMinimumSize(new java.awt.Dimension(3000, 3000));
        fondoRojo.setPreferredSize(new java.awt.Dimension(3000, 3000));
        getContentPane().add(fondoRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1450, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelUserApellidoM;
    private javax.swing.JLabel LabelUserApellidoP;
    private javax.swing.JLabel LabelUserMotivo;
    private javax.swing.JLabel LabelUserName;
    private javax.swing.JButton btnEndUser;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIdentificacion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel fondoRojo;
    private javax.swing.JLabel imgUser;
    private javax.swing.JScrollPane inputApellidoM;
    private javax.swing.JScrollPane inputApellidoP;
    private javax.swing.JScrollPane inputMotivo;
    private javax.swing.JScrollPane inputName;
    private javax.swing.JButton irRegistrar;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JTextArea jTextInputApellidoM;
    private javax.swing.JTextArea jTextInputApellidoP;
    private javax.swing.JTextArea jTextInputName;
    private javax.swing.JTextArea jTextinputMotivo;
    private javax.swing.JLabel meessege;
    private javax.swing.JLabel nameSist;
    private javax.swing.JLabel nameUACM;
    private javax.swing.JLabel userCarr;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
